### ISSUE TITLE
fast_cluster.py not calculating distances

### ISSUE THREAD

**Issue by thomcuddihy** [johnlees/efficient-bge#2]
Line 92 of fast_cluster.py:
`elif not os.path.isfile(str(args.embedding_file)) and not args.hier:`

This prevents mash distances calculation when not using a pre-computed distance matrix, no t-SNE embedding file, and hierarchal clustering (i.e. the example used on the README.md: `python fast_cluster.py --assembly assemblies.txt --output clusters --hier --clusters 22`).

Is this intended behaviour?

**Comment by johnlees** [comment]
That's meant to be in the embedding section, not the distance calculation. Thanks for pointing out.
