### ISSUE TITLE
pip installable?

### ISSUE THREAD

**Issue by tseemann** [johnlees/efficient-bge#4]
Any chance you can make this `pip` installable
Will aid `bioconda` packaging w/ deps.

**Comment by johnlees** [comment]
I don't want to support this repo too much as I've never properly tested and benchmarked its performance across datasets.
Also we've been working on a different method which solves the same problem, but I think in a better way – once we release that I'll definitely put it on `pip`!

**Comment by tseemann** [comment]
Ok no worries.  It's annoying but good when first attempt leads to a new better attempt!
